# docker-compose.prod.yml

version: '3.7'

services:
  backend:
    image: 'willnotwish/dl-backend:latest'
    ports:
      - '8001:8001'
    devices:
      - '/dev/mem:/dev/mem'
    cap_add:
      - sys_rawio
    env_file:
      - .env/production/.auth0.env

  frontend:
    image: 'willnotwish/dl-frontend:latest'
    ports:
      - '80:80'
