# docker-compose.prod.yml

version: '3.6'

services:
  backend:
    image: 'willnotwish/dl-backend:latest'
    ports:
      - '8001:8001'
    devices:
      - '/dev/mem:/dev/mem'
    cap_add:
      - sys_rawio
    env_file:
      - .env/production/.auth0.env

  frontend:
    image: 'willnotwish/dl-frontend:latest'
    ports:
      - '80:80'

  serial:
    image: 'willnotwish/serial-port:latest'
    devices:
      - '/dev/ttyS0:/dev/ttyS0'
    cap_add:
      - sys_rawio
    environment:
      - DEVICE=/dev/ttyS0
      - PUSHER_APP_ID=758098
      - PUSHER_APP_KEY=5b6bc4f109e5cb514bb1
      - PUSHER_APP_SECRET=d59424493a31b8719d50
      - PUSHER_APP_CLUSTER=eu
    stdin_open: true
    tty: true
    command: 'node src/main.js'